apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dsproject-app
spec:
  project: default
  source:
    repoURL: https://git.lab.sspcloud.fr/avouacr/poc_kubernetes.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-avouacr
  syncPolicy:
    automated:
      selfHeal: true
